# Generated by Django 4.0.6 on 2023-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_third'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fcontent', models.TextField(max_length=10000000)),
            ],
        ),
    ]
