# Generated by Django 4.0.6 on 2023-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_sixth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seventh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Secontent', models.TextField(max_length=10000000)),
            ],
        ),
    ]
